<?php

namespace SolarData\Tests;

use PHPUnit\Framework\TestCase;
use SolarData\SolarData;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2017-04-25 at 10:43:26.
 */
class SolarDataTest extends TestCase
{
    /**
     * @var SolarData
     */
    protected $mock;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() : void
    {
        $this->mock = new SolarData();
        $this->mock->setDebug(true);
    }

    /**
     * @covers SolarData\SolarData::setObserverPosition
     *
     * @todo   Implement testSetObserverPosition().
     */
    public function testSetObserverPosition()
    {
        $this->mock->setObserverPosition(31, -7, 400);
        $this->assertSame(
                [
            (float) 31,
            (float) -7,
            (float) 400,
                ], [
            $this->mock->getObserver()->ObserverPosition->latitude,
            $this->mock->getObserver()->ObserverPosition->longitude,
            $this->mock->getObserver()->ObserverPosition->altitude,
        ]);
    }

    /**
     * @covers SolarData\SolarData::setObserverDate
     *
     * @todo   Implement testSetObserverDate().
     */
    public function testSetObserverDate()
    {
        $this->mock->setObserverDate(2000, 1, 1);
        $this->assertSame(
                [
            (float) 2000,
            (float) 1,
            (float) 1,
                ], [
            $this->mock->getObserver()->ObserverTime->Year,
            $this->mock->getObserver()->ObserverTime->Month,
            $this->mock->getObserver()->ObserverTime->Day,
        ]);
    }

    /**
     * @covers SolarData\SolarData::setObserverTime
     *
     * @todo   Implement testSetObserverTime().
     */
    public function testSetObserverTime()
    {
        $this->mock->setObserverTime(12, 0);
        $this->assertSame(
                [
            (float) 12,
            (float) 0,
            (float) 0,
                ], [
            $this->mock->getObserver()->ObserverTime->Hour,
            $this->mock->getObserver()->ObserverTime->Minute,
            $this->mock->getObserver()->ObserverTime->Second,
        ]);
    }

    public function dataProviderTableA4_julianDay()
    {
        return [
            [2000, 1, 1, 12, 0, 2451545.0],
            [1999, 1, 1, 0, 0, 2451179.5],
            [1987, 1, 27, 0, 0, 2446822.5],
            [1987, 6, 19, 12, 0, 2446966.0],
            [1988, 1, 27, 0, 0, 2447187.5],
            [1988, 6, 19, 12, 0, 2447332.0],
            [1900, 1, 1, 0, 0, 2415020.5],
            [1600, 1, 1, 0, 0, 2305447.5],
            [1600, 12, 31, 0, 0, 2305812.5],
            [837, 4, 10, 7, 12, 2026871.8],
            [-123, 12, 31, 0, 0, 1676496.5],
            [-122, 1, 1, 0, 0, 1676497.5],
            [-1000, 7, 12, 12, 0, 1356001.0],
            [-1000, 2, 29, 0, 0, 1355866.5],
            [-1001, 8, 17, 21, 36, 1355671.4],
            [-4712, 1, 1, 12, 0, 0.0],
        ];
    }

    /**
     * @dataProvider dataProviderTableA4_julianDay
     */
    public function testGetJulianDay($year, $month, $day, $hour, $minute, $result)
    {
        $this->mock->setObserverDate($year, $month, $day);
        $this->mock->setObserverTime($hour, $minute);
        $this->mock->calculate();

        $this->assertEqualsWithDelta($result, $this->mock->getObserver()->ObserverTime->JulianDay, 1 / 1e6);
    }

    private function prepareTestCase()
    {
        $this->mock->setObserverPosition(39.742476, -105.1786, 1830.14);

        $this->mock->setObserverDate(2003, 10, 17);

        $this->mock->setObserverTime(12, 30, 30);
        $this->mock->setDeltaTime(67.0);
        $this->mock->setObserverTimezone(-7.0);

        $this->mock->setObserverAtmosphericPressure(820);
        $this->mock->setObserverAtmosphericTemperature(11.0);

        $this->mock->calculate();

        return $this->mock->SunPosition;
    }

    public function testA5_Example_Test_JD()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta(2452930.312847, $this->mock->SunPosition->JD, 1 / 1e6);
    }

    public function testA5_Example_Test_ArrayL()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta([
            172067561.526586,
            628332010650.051147,
            61368.682493,
            -26.902819,
            -121.279536,
            -0.999999,
        ], $this->mock->SunPosition->TEST_UNIT_L, 1 / 1e6);
    }

    public function testA5_Example_Test_L()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta(24.0182616917, $this->mock->SunPosition->L°, 1 / 1e10);
    }

    public function testA5_Example_Test_ArrayB()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta([
            -176.502688,
            3.067582,
        ], $this->mock->SunPosition->TEST_UNIT_B, 1 / 1e6);
    }

    public function testA5_Example_Test_B()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta(-0.0001011219, $this->mock->SunPosition->B°, 1 / 1e10);
    }

    public function testA5_Example_Test_R()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta(0.9965422974, $this->mock->SunPosition->R, 1 / 1e10);
    }

    public function testA5_Example_Test_ArrayR()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta([
            99653849.037796,
            100378.567146,
            -1140.953507,
            -141.115419,
            1.232361,
        ], $this->mock->SunPosition->TEST_UNIT_R, 1 / 1e6);
    }

    public function dataProviderSunPositionVars()
    {
        return [
            ['ObsPressure', 820, 1 / 1e0],
            ['ObsTemperature', 11, 1 / 1e0],
            ['Θ°', 204.0182616917, 1 / 1e10],
            ['β°',  0.0001011219, 1 / 1e10],
            ['Δψ°', -0.00399840, 1 / 1e8],
            ['Δε°',  0.00166657, 1 / 1e8],
            ['ε°', 23.440465, 1 / 1e6],
            ['e°', 39.888377, 1 / 1e6],
            ['e0°', 39.872045, 1 / 1e6],
            ['Δe°',  0.016332, 1 / 1e6],
            ['λ°', 204.0085519281, 1 / 1e10],
            ['α°', 202.2274078, 1 / 1e7],
            ['Δα°', -0.0003685, 1 / 1e7],
            ['α´°', 202.2270392, 1 / 1e6],
            ['ξ°',  0.0024512534, 1 / 1e8],
            ['δ°', -9.31434, 1 / 1e5],
            ['H°', 11.1059, 1 / 1e4],
            ['H´°', 11.10629, 1 / 1e4],
            ['δ´°', -9.316179, 1 / 1e6],
            ['ν°', 318.5119098411, 1 / 1e10],
            ['ν0°', 318.515578272, 1 / 1e9],
            ['Z°', 50.11162, 1 / 1e5],
            ['Φ°', 194.34024, 1 / 1e5],
        ];
    }

    /**
     * @dataProvider dataProviderSunPositionVars
     */
    public function testSunPositionVars($varName, $exceptedResult, $precision)
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta($exceptedResult, $this->mock->SunPosition->$varName, $precision);
    }

    public function testEquationOfTime()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta(14.641503, $this->mock->getEquationOfTime(), 1 / 1e4);
    }

    public function testSunMeanLongitude()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta(
            205.8971722516, $this->mock->SunPosition->getSunMeanLongitude(), 1 / 1e10
        );
    }

    public function testSurfaceIncidenceAngle()
    {
        $this->prepareTestCase();
        $this->assertEqualsWithDelta(
            25.18700, $this->mock->getSurfaceIncidenceAngle(30, -10), 1 / 1e5
        );
    }

    public function dataProviderSUN_rise_transit_set()
    {
        $sun_data = [];

        for ($a = 0; $a < 600; $a++) {
            $randomDate = rand(-81101347200, 64060588800);

            $Date = new \DateTime();
            $Date->setTimestamp($randomDate);

            $sun_info = date_sun_info($randomDate, 31.7667, 35.2333);

            $tmp = [];
            $tmp[] = $randomDate;
            $tmp[] = [
            'sunrise' 	=> $sun_info['sunrise'],
            'transit' 	=> $sun_info['transit'],
            'sunset' 	 => $sun_info['sunset'],
            ];

            $sun_data[] = $tmp;
        }

        return $sun_data;
    }

    /**
     * @dataProvider dataProviderSUN_rise_transit_set
     */
    public function testDataTestSunInfoPHP($datatime, $sundata)
    {
        $Date = new \DateTime();
        $Date->setTimestamp($datatime);

        $this->mock->setObserverPosition(31.7667, 35.2333, 0);

        $this->mock->setObserverDate($Date->format('Y'), $Date->format('m'), $Date->format('d'));

        $this->mock->setObserverTime(12, 30, 30);

        $this->mock->calculate();
        $this->mock->calculateSunRiseTransitSet();

        $Date->setTime(0, 0, 0);
        $HourZeroDate = $Date->getTimestamp();

        $sunrise = date('H:i', $sundata['sunrise']);
        $transit = date('H:i', $sundata['transit']);
        $sunset = date('H:i', $sundata['sunset']);

        $SPA_HM_sunrise = $this->getTestHMfromHMS($this->mock->SunPosition->_DayFracToTime($this->mock->SunPosition->DayFractionSunrise));
        $SPA_HM_transit = $this->getTestHMfromHMS($this->mock->SunPosition->_DayFracToTime($this->mock->SunPosition->DayFractionTransit));
        $SPA_HM_sunset = $this->getTestHMfromHMS($this->mock->SunPosition->_DayFracToTime($this->mock->SunPosition->DayFractionSunset));

        $ZTSunrise_check = $this->mock->SunPosition->_DayFracToHours($this->mock->SunPosition->DayFractionSunrise) * 60 * 60;
        $ZTTransit_check = $this->mock->SunPosition->_DayFracToHours($this->mock->SunPosition->DayFractionTransit) * 60 * 60;
        $ZTSunset_check = $this->mock->SunPosition->_DayFracToHours($this->mock->SunPosition->DayFractionSunset) * 60 * 60;

        $ZTSunrise = ($sundata['sunrise'] - $HourZeroDate);
        $ZTTransit = ($sundata['transit'] - $HourZeroDate);
        $ZTSunset = ($sundata['sunset'] - $HourZeroDate);

        $this->assertEqualsWithDelta([
                abs($ZTSunrise - $ZTSunrise_check),
                abs($ZTTransit - $ZTTransit_check),
                abs($ZTSunset - $ZTSunset_check),
            ], [
                0,
                0,
                0,
            ],
            15 * 60 // Maximum error +/- 15 Minutes
            , ' For date : '.$Date->format('Y-m-d').PHP_EOL
                .date('H:i', $ZTSunrise).' is out of tollerance error respect '.date('H:i', $ZTSunrise_check).PHP_EOL
                .date('H:i', $ZTTransit).' is out of tollerance error respect '.date('H:i', $ZTTransit_check).PHP_EOL
                .date('H:i', $ZTSunset).' is out of tollerance error respect '.date('H:i', $ZTSunset_check).PHP_EOL
            );
    }

    private function getTestHMfromHMS($timeHMS)
    {
        $chunk = explode(':', $timeHMS);

        return $chunk[0].':'.$chunk[1];
    }
}
